apiVersion: batch/v1
kind: Job
metadata:
  name: sb-shell
spec:
  template:
    spec:
      containers:
        - args:
            - hello --name "Spring Shell"
          image: $IMAGE_NAME
          name: sb-shell
          imagePullPolicy: IfNotPresent
      restartPolicy: Never